# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efeedd2eb076a36cea36cdaf4ba8b01a8a7ed101ffbb6fd46d738fd053d76777687eb36aff3f3889159059823cfd2097c3b3c26c897efefe8bfc8542626073ad

test:
  secret_key_base: 5d1cb7f4e7f50bfb5921195eab426bf2ad1e95045747987225a9c9acfb5f629249dc06719cc942466e28667c1a53eb36b851b31742baea0864fc83492fe506ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
